services:
  keydb:
    image: eqalpha/keydb:x86_64_v6.3.3
    container_name: keydb
    restart: unless-stopped
    ports:
      - "${KEYDB_PORT:-6739}:6379"
    volumes:
      - keydb_data:/data
    command: keydb-server /etc/keydb/keydb.conf --requirepass ${KEYDB_PASSWORD}
volumes:
  keydb_data:
